rootUrl: http://127.0.0.1:8080/components/vaadin-icons/test/visual/
gridUrl: http://127.0.0.1:4444/wd/hub
screenshotsDir: ./test/visual/screens
compositeImage: true

system:
  plugins:
    polyserve:
      port: 8080
    sauce: true

browsers:
  ie:
    desiredCapabilities:
      browserName: "internet explorer"
      version: "11.0"
      platform: "Windows 10"
